name: mercado_local_movil
description: Aplicación móvil para MercadoLocal-IA.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Necesarios para tu app
  provider: ^6.1.1
  dio: ^5.4.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/imagenes/Logo2.png
