name: mercado_local_movil
description: Aplicación móvil para MercadoLocal-IA.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  dio: ^5.4.0
  http: ^1.6.0

  # ⭐ Necesario para guardar token y usuario
  shared_preferences: ^2.2.2

  # ⭐ Tu librería del nav estético
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/imagenes/
